"""
NAICS Rankings Page Logic

Aggregates company scoring data by NAICS code to show industry-level attractiveness.
"""

import pandas as pd
import streamlit as st


def get_naics_description(naics_code):
    """
    Get human-readable description for NAICS code.

    For 4-digit codes, returns industry group names.
    For 6-digit codes, returns specific industry names.
    """
    # Map 4-digit NAICS to industry group descriptions
    naics_4digit_map = {
        '6214': 'Outpatient Care Centers',
        '6221': 'General Medical and Surgical Hospitals',
        '5413': 'Architectural, Engineering, and Related Services',
        '6211': 'Offices of Physicians and Dentists',
        '6216': 'Home Health Care Services',
        '6219': 'Other Ambulatory Health Care Services',
        '6231': 'Nursing and Residential Care Facilities',
        '2361': 'Residential Building Construction',
        '2372': 'Land Subdivision',
        '2382': 'Building Equipment Contractors',
        '3254': 'Pharmaceutical and Medicine Manufacturing',
        '3345': 'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing',
        '4234': 'Professional and Commercial Equipment and Supplies Merchant Wholesalers',
        '3391': 'Medical Equipment and Supplies Manufacturing',
    }

    naics_str = str(int(naics_code)) if pd.notna(naics_code) else ''

    # Try exact match for 4-digit codes first
    if len(naics_str) >= 4:
        naics_4digit = naics_str[:4]
        if naics_4digit in naics_4digit_map:
            return naics_4digit_map[naics_4digit]

    # Otherwise, return category based on first 2 digits
    if naics_str.startswith('62'):
        return f'Healthcare Services ({naics_str})'
    elif naics_str.startswith('54'):
        return f'Professional Services ({naics_str})'
    elif naics_str.startswith('23'):
        return f'Construction ({naics_str})'
    elif naics_str.startswith('32'):
        return f'Manufacturing ({naics_str})'
    elif naics_str.startswith('42'):
        return f'Wholesale Trade ({naics_str})'
    elif naics_str.startswith('44') or naics_str.startswith('45'):
        return f'Retail Trade ({naics_str})'
    elif naics_str.startswith('33'):
        return f'Manufacturing ({naics_str})'
    else:
        return f'NAICS {naics_str}'


def aggregate_naics_rankings(scored_df):
    """
    Load NAICS rankings from the metrics file generated by scoring script.

    Args:
        scored_df: DataFrame with scored companies (used for company counts)

    Returns:
        DataFrame with one row per NAICS code (6-digit), sorted by attractiveness
    """
    from pathlib import Path

    # Load NAICS metrics file
    naics_metrics_path = Path("data/scoring/naics_metrics.csv")

    if not naics_metrics_path.exists():
        # Fallback: aggregate from scored companies if metrics file doesn't exist
        import streamlit as st
        st.error(f"NAICS metrics file not found: {naics_metrics_path}. Run scoring script to generate it.")
        return pd.DataFrame()

    naics_df = pd.read_csv(naics_metrics_path)

    # Rename icp_fit_reasoning to reasoning for consistency in UI
    if 'icp_fit_reasoning' in naics_df.columns:
        naics_df['reasoning'] = naics_df['icp_fit_reasoning']
    else:
        naics_df['reasoning'] = None

    # Convert naics_code to string for proper merging later
    naics_df['naics_code'] = naics_df['naics_code'].astype(str)

    # Add company count by grouping scored companies by 4-digit NAICS
    if 'naics_4digit' in scored_df.columns:
        # Use existing naics_4digit column from scored_companies_final.csv
        company_counts = scored_df.groupby('naics_4digit').agg({
            'company_id': 'count',
            'is_customer': 'sum'  # Count customers (is_customer is boolean/int)
        }).reset_index()
        company_counts.columns = ['naics_code', 'company_count', 'customer_count']

        # Ensure naics_code is string for proper merging
        company_counts['naics_code'] = company_counts['naics_code'].astype(str)

        # Merge counts into naics_df
        naics_df = naics_df.merge(company_counts, on='naics_code', how='left')

        # Fill NaN values with 0 for NAICS codes that have no companies
        naics_df['company_count'] = naics_df['company_count'].fillna(0).astype(int)
        naics_df['customer_count'] = naics_df['customer_count'].fillna(0).astype(int)
    else:
        # If naics_4digit column doesn't exist, set defaults
        naics_df['company_count'] = 0
        naics_df['customer_count'] = 0

    naics_df['prospect_count'] = naics_df['company_count'] - naics_df['customer_count']

    # Use NAICS descriptions from CSV if available, otherwise generate them
    if 'naics_description' not in naics_df.columns or naics_df['naics_description'].isna().all():
        naics_df['naics_description'] = naics_df['naics_code'].apply(get_naics_description)
    else:
        # Fill missing descriptions with generated ones
        naics_df['naics_description'] = naics_df.apply(
            lambda row: row['naics_description'] if pd.notna(row.get('naics_description'))
            else get_naics_description(row['naics_code']),
            axis=1
        )

    # Sort by attractiveness score
    naics_df = naics_df.sort_values('attractiveness_score', ascending=False)

    # Reorder columns - show component scores instead of company stats
    # Exclude rank and penetration_opp_score (not used in scoring)
    naics_df = naics_df[[
        'naics_code',
        'naics_description',
        'attractiveness_score',
        'company_count',
        'customer_count',
        'prospect_count',
        'icp_fit_score',
        'profitability_score',
        'market_size_score',
        'market_size_count',
        'churn_health_score',
        'ticket_health_score',
        'reasoning'
    ]]

    return naics_df


def get_score_color(score):
    """
    Return color for score tier.

    Per PRD:
    - Green (80+)
    - Yellow (60-79)
    - Red (<60)
    """
    if score >= 80:
        return '#28a745'  # Green
    elif score >= 60:
        return '#ffc107'  # Yellow
    else:
        return '#dc3545'  # Red


def display_naics_rankings(scored_df):
    """
    Display NAICS rankings table with sortable columns and click-through.

    Args:
        scored_df: DataFrame with scored companies
    """
    st.title("NAICS Industry Rankings")
    st.markdown("""
    Industries ranked by attractiveness score, combining ICP fit, OpenWorks operational metrics
    (revenue concentration, building count, revenue per building), market size, and customer health metrics
    (churn and support tickets).
    """)

    # Aggregate data
    naics_df = aggregate_naics_rankings(scored_df)

    # Display summary metrics
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Total Industries", len(naics_df))
    with col2:
        top_score = naics_df['attractiveness_score'].max()
        st.metric("Top Score", f"{top_score:.1f}")
    with col3:
        total_companies = naics_df['company_count'].sum()
        st.metric("Total Companies", f"{total_companies:,}")

    st.markdown("---")

    # Add sorting controls
    sort_col1, sort_col2 = st.columns([3, 1])
    with sort_col1:
        sort_by = st.selectbox(
            "Sort by",
            options=[
                'attractiveness_score',
                'company_count',
                'icp_fit_score',
                'profitability_score',
                'market_size_score',
                'churn_health_score',
                'ticket_health_score'
            ],
            format_func=lambda x: {
                'attractiveness_score': 'Attractiveness Score',
                'company_count': 'Company Count',
                'icp_fit_score': 'ICP Fit',
                'profitability_score': 'Profitability',
                'market_size_score': 'Market Size',
                'churn_health_score': 'Churn Health',
                'ticket_health_score': 'Ticket Health'
            }[x],
            index=0  # Default to attractiveness_score
        )
    with sort_col2:
        sort_order = st.radio("Order", ['Descending', 'Ascending'], horizontal=True)

    # Apply sorting
    ascending = (sort_order == 'Ascending')
    naics_df_sorted = naics_df.sort_values(sort_by, ascending=ascending)

    # Display table with color coding
    st.markdown("### Industry Rankings")

    # Display industries with expandable reasoning
    for idx, row in naics_df_sorted.iterrows():
        color = get_score_color(row['attractiveness_score'])

        # Create expandable container for each industry
        with st.expander(
            f"**{row['naics_description']}** (NAICS: {row['naics_code']}) — "
            f"Score: {row['attractiveness_score']:.1f}",
            expanded=False
        ):
            # Score metrics in columns
            col1, col2, col3, col4 = st.columns(4)

            with col1:
                st.metric("Attractiveness", f"{row['attractiveness_score']:.1f}")
                if pd.notna(row.get('icp_fit_score')):
                    st.metric("ICP Fit", f"{row['icp_fit_score']:.1f}")

            with col2:
                if pd.notna(row.get('profitability_score')):
                    st.metric("Profitability", f"{row['profitability_score']:.1f}")
                if pd.notna(row.get('market_size_score')):
                    st.metric("Market Size", f"{row['market_size_score']:.1f}")

            with col3:
                if pd.notna(row.get('churn_health_score')):
                    st.metric("Churn Health", f"{row['churn_health_score']:.1f}")
                if pd.notna(row.get('ticket_health_score')):
                    st.metric("Ticket Health", f"{row['ticket_health_score']:.1f}")

            with col4:
                st.metric("Companies", f"{row.get('company_count', 0):.0f}")
                if pd.notna(row.get('market_size_count')):
                    st.metric("Market Size", f"{row['market_size_count']:,.0f}")

            # ICP Fit Reasoning
            if pd.notna(row.get('reasoning')) and row.get('reasoning'):
                st.markdown("---")
                st.markdown("**🎯 ICP Fit Justification:**")
                st.markdown(f"_{row['reasoning']}_")
            else:
                st.info("ICP justification not available for this industry.")

            # Navigation button to view companies in this NAICS
            st.markdown("---")
            company_count = int(row.get('company_count', 0))
            if company_count > 0:
                if st.button(
                    f"🔍 View {company_count} Companies in this Industry",
                    key=f"view_naics_{row['naics_code']}",
                    use_container_width=True
                ):
                    # Set session state to pre-filter on the target page
                    st.session_state['naics_filter_from_rankings'] = str(row['naics_code'])
                    st.switch_page("pages/1_ranked_companies.py")
            else:
                st.info("No companies in this industry in the current dataset.")

    # Add data dictionary
    st.markdown("---")
    st.markdown("### 📖 Score Component Dictionary")

    st.markdown("""
    Understanding what drives industry attractiveness:

    | Component | Description | Range | Weight | Details |
    |-----------|-------------|-------|--------|---------|
    | **Attractiveness Score** | Overall industry attractiveness combining all factors below | 0-100 | 100% | Higher = more attractive industry |
    | **ICP Fit Score** | Claude AI assessment of industry alignment with OpenWorks' ideal customer profile | 0-100 | 25% | Evaluates facility needs, multi-location potential, regulatory requirements, similarity to existing customers, and historical OpenWorks performance data. |
    | **Market Size Score** | Nationwide market size in this industry | 0-100 | 15% | Log-scaled: 1 location = 0, 100,000+ locations = 100. Based on DataAxle nationwide counts. |
    | **Market Size Count** | Actual count of locations nationwide for this NAICS code | 1+ | — | Reference metric showing total addressable market (not used in scoring calculation). |
    | **OW Revenue Concentration** | OpenWorks' revenue concentration in this industry | 0-100 | 15% | Percentage of total OpenWorks revenue from this NAICS. Log-scaled: 5%+ revenue = ~100, 1-5% = 60-90, <1% = 20-60. No presence = 0. |
    | **OW Building Count** | OpenWorks operational scale in this industry | 0-100 | 20% | Number of buildings OpenWorks currently serves in this NAICS. Log-scaled: 1 building = 20, 100+ buildings = 90-100. No presence = 0. |
    | **Revenue per Building** | OpenWorks revenue quality in this industry | 0-100 | 5% | Average monthly revenue per building for this NAICS, compared to median across all NAICS. Above median = 50-100, below median = 0-50, no presence = 50 (neutral). |
    | **Churn Health Score** | Customer retention health in this industry | 0-100 | 15% | Based on historical churn predictions. Higher retention = higher attractiveness. |
    | **Ticket Health Score** | Support ticket quality/volume health in this industry | 0-100 | 5% | Based on semantic analysis of support tickets. Fewer/better tickets = higher attractiveness. |
    | **Profitability Score** | Industry profit margin (reference only) | 0-100 | 0% | Calculated from OpenWorks data (0-40% margin → 0-100 score) but not included in attractiveness score. |

    **Formula**: Attractiveness = ICP Fit (25%) + Market Size (15%) + OW Revenue Concentration (15%) + OW Building Count (20%) + Revenue per Building (5%) + Churn Health (15%) + Ticket Health (5%)

    **ICP Fit Justification**: Each industry has a detailed AI-generated justification explaining why it does or doesn't fit OpenWorks' Ideal Customer Profile. The AI analysis is informed by actual OpenWorks historical performance data including revenue, building counts, customer success patterns, and operational metrics. Click on any industry above to see the full reasoning.

    **OpenWorks Operational Metrics**: Industries where OpenWorks has existing presence and strong operational metrics (high revenue concentration, many buildings, good revenue per building) receive higher attractiveness scores. This reflects proven success and scalability in those verticals.

    **Note**: Missing scores (shown as "—") indicate no data available for that component. The attractiveness score is normalized based on available components only. Industries with no OpenWorks presence receive 0 scores for OW-specific metrics (Revenue Concentration, Building Count) but neutral scores (50) for Revenue per Building.
    """)

    # Add click-through instructions
    st.info(
        "💡 **Tip**: Click the '🔍 View Companies' button in any industry to navigate "
        "to the **Ranked Companies** page with that NAICS pre-filtered."
    )

    # Show top 10 in expander with ICP reasoning
    with st.expander("📊 Top 10 Most Attractive Industries", expanded=True):
        top_10 = naics_df.head(10)

        for rank, (idx, row) in enumerate(top_10.iterrows(), start=1):
            color = get_score_color(row['attractiveness_score'])

            # Build component scores string
            components = []
            if pd.notna(row.get('icp_fit_score')):
                components.append(f"ICP Fit: {row['icp_fit_score']:.1f}")
            if pd.notna(row.get('profitability_score')):
                components.append(f"Profitability: {row['profitability_score']:.1f}")
            if pd.notna(row.get('market_size_score')):
                components.append(f"Market Size: {row['market_size_score']:.1f} ({row.get('market_size_count', 0):.0f} companies)")
            if pd.notna(row.get('churn_health_score')):
                components.append(f"Churn Health: {row['churn_health_score']:.1f}")
            if pd.notna(row.get('ticket_health_score')):
                components.append(f"Ticket Health: {row['ticket_health_score']:.1f}")

            components_str = " | ".join(components) if components else "No component data"

            st.markdown(f"""
            **#{rank}. {row['naics_description']}** (NAICS: {row['naics_code']})
            - Score: <span style='background-color: {color}; color: white; padding: 2px 8px; border-radius: 3px; font-weight: bold'>{row['attractiveness_score']:.1f}</span>
            - Companies: {row.get('company_count', 0):.0f}
            - {components_str}
            """, unsafe_allow_html=True)

            # Add ICP reasoning for top industries
            if pd.notna(row.get('reasoning')) and row.get('reasoning'):
                st.markdown(f"**Why This Industry Fits**: _{row['reasoning']}_")

            # Quick navigation button for top 10
            company_count = int(row.get('company_count', 0))
            if company_count > 0:
                if st.button(
                    f"View Companies →",
                    key=f"view_top10_{row['naics_code']}",
                    type="secondary"
                ):
                    # Set session state to pre-filter on the target page
                    st.session_state['naics_filter_from_rankings'] = str(row['naics_code'])
                    st.switch_page("pages/1_ranked_companies.py")

            st.markdown("---")

    return naics_df
